language: python
python:
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"

# command to install dependencies
install:
  - pip install .
  - pip install -r requirements.txt

script:
  - python tests/test_menu.py
  - python tests/test_menupoint.py

branches:
  only:
    - master


